-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2023-07-13 21:02:30.546

-- tables
-- Table: CLIENTE
CREATE TABLE CLIENTE (
    CODCLI char(4)  NOT NULL,
    NOMCLI varchar(60)  NOT NULL,
    APECLI varchar(80)  NOT NULL,
    EMACLI varchar(80)  NOT NULL,
    CELCLI char(9)  NOT NULL,
    DIRCLI varchar(70)  NOT NULL,
    ESTCLI char(1)  NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (CODCLI)
);

-- Table: COMPRA
CREATE TABLE COMPRA (
    CODCOM char(5)  NOT NULL,
    FECCOM datetime  NOT NULL,
    CODPROV char(4)  NOT NULL,
    CODVEND char(5)  NOT NULL,
    ESTCOM char(1)  NOT NULL,
    VENDEDOR_CODVEND char(4)  NOT NULL,
    PROVEDOR_CODPROV char(5)  NOT NULL,
    CONSTRAINT COMPRA_pk PRIMARY KEY (CODCOM)
);

-- Table: COMPRADETALLE
CREATE TABLE COMPRADETALLE (
    IDCOMDET int  NOT NULL,
    CODCOM char(5)  NOT NULL,
    CODPRO char(5)  NOT NULL,
    CANTPRO int  NOT NULL,
    COMPRA_CODCOM char(5)  NOT NULL,
    PRODUCTO_CODPRO char(5)  NOT NULL,
    CONSTRAINT COMPRADETALLE_pk PRIMARY KEY (IDCOMDET)
);

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    CODPRO char(5)  NOT NULL,
    DESCPRO varchar(80)  NOT NULL,
    CATPRO char(1)  NOT NULL,
    PREPRO decimal(8,2)  NOT NULL,
    STOCKPRO int  NOT NULL,
    ESTPRO char(1)  NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (CODPRO)
);

-- Table: PROVEDOR
CREATE TABLE PROVEDOR (
    CODPROV char(5)  NOT NULL,
    RAZSOCPROV varchar(90)  NOT NULL,
    RUCPROV varchar(11)  NOT NULL,
    EMAPROV varchar(70)  NOT NULL,
    ESTPROV char(1)  NOT NULL,
    CONSTRAINT PROVEDOR_pk PRIMARY KEY (CODPROV)
);

-- Table: VENDEDOR
CREATE TABLE VENDEDOR (
    CODVEND char(4)  NOT NULL,
    NOMVEND varchar(60)  NOT NULL,
    APEVEND varchar(80)  NOT NULL,
    EMAVEND varchar(80)  NOT NULL,
    CELVEND char(9)  NOT NULL,
    DIRVEND varchar(70)  NOT NULL,
    ESTVEND char(1)  NOT NULL,
    CONSTRAINT VENDEDOR_pk PRIMARY KEY (CODVEND)
);

-- Table: VENTA
CREATE TABLE VENTA (
    CODVEN char(5)  NOT NULL,
    FECVEN datetime  NOT NULL,
    CODCLI char(4)  NOT NULL,
    CODVEND char(4)  NOT NULL,
    ESTVEN char(1)  NOT NULL,
    VENDEDOR_CODVEND char(4)  NOT NULL,
    CLIENTE_CODCLI char(4)  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (CODVEN)
);

-- Table: VENTADETALLE
CREATE TABLE VENTADETALLE (
    IDVENDET int  NOT NULL,
    CODVEN char(5)  NOT NULL,
    CODPRO char(5)  NOT NULL,
    CANTPRO int  NOT NULL,
    VENTA_CODVEN char(5)  NOT NULL,
    PRODUCTO_CODPRO char(5)  NOT NULL,
    CONSTRAINT VENTADETALLE_pk PRIMARY KEY (IDVENDET)
);

-- foreign keys
-- Reference: COMPRADETALLE_COMPRA (table: COMPRADETALLE)
ALTER TABLE COMPRADETALLE ADD CONSTRAINT COMPRADETALLE_COMPRA FOREIGN KEY COMPRADETALLE_COMPRA (COMPRA_CODCOM)
    REFERENCES COMPRA (CODCOM);

-- Reference: COMPRADETALLE_PRODUCTO (table: COMPRADETALLE)
ALTER TABLE COMPRADETALLE ADD CONSTRAINT COMPRADETALLE_PRODUCTO FOREIGN KEY COMPRADETALLE_PRODUCTO (PRODUCTO_CODPRO)
    REFERENCES PRODUCTO (CODPRO);

-- Reference: COMPRA_PROVEDOR (table: COMPRA)
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_PROVEDOR FOREIGN KEY COMPRA_PROVEDOR (PROVEDOR_CODPROV)
    REFERENCES PROVEDOR (CODPROV);

-- Reference: COMPRA_VENDEDOR (table: COMPRA)
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_VENDEDOR FOREIGN KEY COMPRA_VENDEDOR (VENDEDOR_CODVEND)
    REFERENCES VENDEDOR (CODVEND);

-- Reference: VENTADETALLE_PRODUCTO (table: VENTADETALLE)
ALTER TABLE VENTADETALLE ADD CONSTRAINT VENTADETALLE_PRODUCTO FOREIGN KEY VENTADETALLE_PRODUCTO (PRODUCTO_CODPRO)
    REFERENCES PRODUCTO (CODPRO);

-- Reference: VENTADETALLE_VENTA (table: VENTADETALLE)
ALTER TABLE VENTADETALLE ADD CONSTRAINT VENTADETALLE_VENTA FOREIGN KEY VENTADETALLE_VENTA (VENTA_CODVEN)
    REFERENCES VENTA (CODVEN);

-- Reference: VENTA_CLIENTE (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE FOREIGN KEY VENTA_CLIENTE (CLIENTE_CODCLI)
    REFERENCES CLIENTE (CODCLI);

-- Reference: VENTA_VENDEDOR (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_VENDEDOR FOREIGN KEY VENTA_VENDEDOR (VENDEDOR_CODVEND)
    REFERENCES VENDEDOR (CODVEND);

-- End of file.

